### ISSUE TITLE
WhatsApp User Agent not right in Daily

### ISSUE THREAD

**Issue by ryanleesipes** [kewisch/birdbox-extension#1]
As discussed, WhatsApp loads properly in Beta, but not in Daily.

![Screenshot 2024-08-18 052935](https://github.com/user-attachments/assets/99e74ff3-460f-41a4-b69e-61aaecd2f7e3)

**Comment by ryanleesipes** [comment]
Daily Useragent: 

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0 Firefox/131.0a1
```

**Comment by ryanleesipes** [comment]
Beta Useragent:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
```

**Comment by kewisch** [comment]
It looks like Geoff changed the pref `general.useragent.compatMode.firefox` on nightly because it was needed for sync, with a TODO fix this comment. I don't think there is anything I can/should do in the extension here, either this will fix itself when Geoff finishes sync support, or users will have the manual UA override in the extension settings.

https://searchfox.org/comm-central/diff/55c6b3fdf112c0d1eefbf7e9c0555051fd60fc32/mail/app/profile/all-thunderbird.js#1366

If you turn that pref off, it will also work :)
